database:
  url: jdbc:postgresql://localhost:5432/tt
  username: postgres
  password: root
  driver: org.postgresql.Driver
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  hbm2ddl_auto: update